using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Avalonia.Markup.Declarative.SourceGenerator;

[Generator]
public class AvaloniaComponentGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static c => c is not null);

        context.RegisterSourceOutput(classDeclarations,
            static (spc, data) => GenerateSource(spc, data));
    }

    private static (ClassDeclarationSyntax Syntax, GeneratorData Data)? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        if (symbol is not INamedTypeSymbol typeSymbol || !InheritsFrom(typeSymbol, "ComponentBase"))
            return null;

        var injectables = new List<(string Name, string Type, bool IsProperty, bool HasSetter)>();
        var notifyables = new List<(string Name, string Type, bool IsProperty)>();

        var currentType = typeSymbol;
        while (currentType != null && currentType.SpecialType != SpecialType.System_Object)
        {
            var members = currentType.GetMembers()
                .Where(m => SymbolEqualityComparer.Default.Equals(m.ContainingType, typeSymbol));

            foreach (var member in members)
            {
                var hasInject = member.GetAttributes().Any(a => a.AttributeClass?.Name is "InjectAttribute" or "Inject");
                var hasNotify = member.GetAttributes().Any(a => a.AttributeClass?.Name is "ObserveAttribute" or "Observe");

                if (hasInject)
                {
                    if (member is IPropertySymbol prop)
                    {
                        injectables.Add((prop.Name, prop.Type.ToDisplayString(), true, !prop.IsReadOnly));
                    }
                    else if (member is IFieldSymbol field)
                    {
                        injectables.Add((field.Name, field.Type.ToDisplayString(), false, !field.IsReadOnly));
                    }
                }

                if (hasNotify)
                {
                    if (member is IPropertySymbol prop)
                    {
                        notifyables.Add((prop.Name, prop.Type.ToDisplayString(), true));
                    }
                    else if (member is IFieldSymbol field)
                    {
                        notifyables.Add((field.Name, field.Type.ToDisplayString(), false));
                    }
                }
            }
            currentType = currentType.BaseType;
        }

        if (injectables.Count == 0 && notifyables.Count == 0)
            return null;

        return (classDecl, new GeneratorData
        {
            Symbol = typeSymbol,
            Injectables = injectables,
            Observables = notifyables
        });
    }

    private static bool InheritsFrom(INamedTypeSymbol symbol, string baseName)
    {
        var current = symbol.BaseType;
        while (current != null)
        {
            if (current.Name == baseName) return true;
            current = current.BaseType;
        }
        return false;
    }

    private static void GenerateSource(SourceProductionContext context, (ClassDeclarationSyntax Syntax, GeneratorData Data)? data)
    {
        if (data == null) 
            return;
        
        var typeSymbol = data.Value.Data.Symbol;
        var className = typeSymbol.Name;
        var injectables = data.Value.Data.Injectables;
        var observables = data.Value.Data.Observables;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using Avalonia.Controls;");
        sb.AppendLine("using Avalonia.Markup.Declarative;");
        sb.AppendLine();

        // Handle Namespace
        if (!typeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {typeSymbol.ContainingNamespace.ToDisplayString()};");
            sb.AppendLine();
        }

        // Handle Nested Classes
        var parents = new Stack<INamedTypeSymbol>();
        var parent = typeSymbol.ContainingType;
        while (parent != null)
        {
            parents.Push(parent);
            parent = parent.ContainingType;
        }

        int indentLevel = 0;

        // Open Parent Classes
        foreach (var p in parents)
        {
            sb.AppendLine($"{Indent(indentLevel)}partial class {p.Name}");
            sb.AppendLine($"{Indent(indentLevel)}{{");
            indentLevel++;
        }

        // Open The Component Class
        sb.AppendLine($"{Indent(indentLevel)}partial class {className}");
        sb.AppendLine($"{Indent(indentLevel)}{{");

        string indent = Indent(indentLevel + 1);

        // Generate InjectServices method if needed
        if (injectables.Count > 0)
        {
            // [DynamicDependency] attributes
            foreach (var item in injectables)
                sb.AppendLine($"{indent}[DynamicDependency(DynamicallyAccessedMemberTypes.PublicConstructors, typeof({item.Type.TrimEnd('?')}))]");

            sb.AppendLine($"{indent}protected override void InjectServices()");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    base.InjectServices();");
            sb.AppendLine();
            sb.AppendLine($"{indent}    if (AppBuilderExtensions.ServiceProvider == null)");
            sb.AppendLine($"{indent}        throw new InvalidOperationException(\"Set AppBuilderExtensions.ServiceProvider to use Dependency Injection\");");
            sb.AppendLine();

            foreach (var item in injectables)
                sb.AppendLine($"{indent}    this.{item.Name} = ({item.Type})AppBuilderExtensions.ServiceProvider.GetService(typeof({item.Type.TrimEnd('?')}));");

            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }

        // Generate SubscribeToNotifyPropertyChangedMembers method if needed
        if (observables.Count > 0)
        {
            sb.AppendLine($"{indent}private readonly HashSet<INotifyPropertyChanged> _trackedNotifyMembers = new();");
            sb.AppendLine();

            sb.AppendLine($"{indent}protected override void SubscribeToNotifyPropertyChangedMembers()");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    base.SubscribeToNotifyPropertyChangedMembers();");
            sb.AppendLine();

            foreach (var item in observables)
            {
                sb.AppendLine($"{indent}    if ({item.Name} != null && _trackedNotifyMembers.Add({item.Name}))");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        {item.Name}.PropertyChanged += OnNotifyMemberPropertyChanged;");
                sb.AppendLine($"{indent}    }}");
            }

            sb.AppendLine($"{indent}}}");
            sb.AppendLine();

            // Generate UnsubscribeToNotifyPropertyChangedMembers override for cleanup
            sb.AppendLine($"{indent}protected override void UnsubscribeToNotifyPropertyChangedMembers()");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    base.UnsubscribeToNotifyPropertyChangedMembers();");
            sb.AppendLine();
            
            foreach (var item in observables)
            {
                sb.AppendLine($"{indent}    if ({item.Name} != null)");
                sb.AppendLine($"{indent}        {item.Name}.PropertyChanged -= OnNotifyMemberPropertyChanged;");
            }
            
            sb.AppendLine();
            sb.AppendLine($"{indent}    // Fail-safe: unsubscribe from all tracked objects in case property was changed");
            sb.AppendLine($"{indent}    foreach (var trackedMember in _trackedNotifyMembers)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (trackedMember != null)");
            sb.AppendLine($"{indent}            trackedMember.PropertyChanged -= OnNotifyMemberPropertyChanged;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}    _trackedNotifyMembers.Clear();");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
            
            // Generate property changed handler
            sb.AppendLine($"{indent}private void OnNotifyMemberPropertyChanged(object? sender, PropertyChangedEventArgs e)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    StateHasChanged();");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }

        sb.AppendLine($"{Indent(indentLevel)}}}"); // Close Component Class

        // Close Parent Classes
        while (parents.Count > 0)
        {
            parents.Pop();
            indentLevel--;
            sb.AppendLine($"{Indent(indentLevel)}}}");
        }

        // Use a unique filename for nested types: "Outer_Inner.Component.g.cs"
        var uniqueName = typeSymbol.ToDisplayString().Replace(".", "_").Replace("<", "").Replace(">", "");
        context.AddSource($"{uniqueName}.Component.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string Indent(int level) => new string(' ', level * 4);

    private class GeneratorData
    {
        public INamedTypeSymbol Symbol { get; set; } = null!;
        public List<(string Name, string Type, bool IsProperty, bool HasSetter)> Injectables { get; set; } = new();
        public List<(string Name, string Type, bool IsProperty)> Observables { get; set; } = new();
    }
}