using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Avalonia.Markup.Declarative.SourceGenerator;

[Generator]
public class AvaloniaDependencyInjectionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static c => c is not null);

        context.RegisterSourceOutput(classDeclarations,
            static (spc, data) => GenerateSource(spc, data.Value.Symbol));
    }

    private static (ClassDeclarationSyntax Syntax, INamedTypeSymbol Symbol)? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        return symbol is INamedTypeSymbol typeSymbol && InheritsFrom(typeSymbol, "ComponentBase")
            ? (classDecl, typeSymbol)
            : null;
    }
    
    private static bool InheritsFrom(INamedTypeSymbol symbol, string baseName)
    {
        var current = symbol.BaseType;
        while (current != null)
        {
            if (current.Name == baseName) return true;
            current = current.BaseType;
        }
        return false;
    }

    private static void GenerateSource(SourceProductionContext context, INamedTypeSymbol typeSymbol)
    {
        var ns = typeSymbol.ContainingNamespace.ToDisplayString();
        var className = typeSymbol.Name;
        
        // Collect all properties/fields with [Inject] attribute from this class and base classes
        var injectables = new List<(string Name, string Type, bool IsProperty, bool HasSetter)>();
        
        var currentType = typeSymbol;
        while (currentType != null && currentType.SpecialType != SpecialType.System_Object)
        {
            var members = currentType.GetMembers()
                .Where(m => m.GetAttributes().Any(a => a.AttributeClass?.Name is "InjectAttribute" or "Inject"))
                .Where(m => SymbolEqualityComparer.Default.Equals(m.ContainingType, typeSymbol));

            foreach (var member in members)
            {
                if (member is IPropertySymbol prop)
                {
                    injectables.Add((prop.Name, prop.Type.ToDisplayString(), true, !prop.IsReadOnly));
                }
                else if (member is IFieldSymbol field)
                {
                    injectables.Add((field.Name, field.Type.ToDisplayString(), false, !field.IsReadOnly));
                }
            }
            currentType = currentType.BaseType;
        }

        if (injectables.Count == 0) return;

       var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using Avalonia.Markup.Declarative;");
        sb.AppendLine();
        
        // Handle Namespace
        if (!typeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {typeSymbol.ContainingNamespace.ToDisplayString()};");
            sb.AppendLine();
        }

        // 3. Handle Nested Classes (e.g. public class Tests { public class View ... })
        // We need to recreate the class nesting structure for the partial to work.
        var parents = new Stack<INamedTypeSymbol>();
        var parent = typeSymbol.ContainingType;
        while (parent != null)
        {
            parents.Push(parent);
            parent = parent.ContainingType;
        }

        int indentLevel = 0;
        
        // Open Parent Classes
        foreach (var p in parents)
        {
            sb.AppendLine($"{new string(' ', indentLevel * 4)}partial class {p.Name}");
            sb.AppendLine($"{new string(' ', indentLevel * 4)}{{");
            indentLevel++;
        }

        // Open The View Class
        sb.AppendLine($"{new string(' ', indentLevel * 4)}partial class {className}");
        sb.AppendLine($"{new string(' ', indentLevel * 4)}{{");
        
        string indent = new string(' ', (indentLevel + 1) * 4);

        // [DynamicDependency] attributes
        foreach (var item in injectables)
            sb.AppendLine($"{indent}[DynamicDependency(DynamicallyAccessedMemberTypes.PublicConstructors, typeof({item.Type.TrimEnd('?')}))]");

        sb.AppendLine($"{indent}protected override void InjectServices()");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    base.InjectServices();");
        sb.AppendLine();
        sb.AppendLine($"{indent}    if (AppBuilderExtensions.ServiceProvider == null)");
        sb.AppendLine($"{indent}        throw new InvalidOperationException(\"Set AppBuilderExtensions.ServiceProvider to use Dependency Injection\");");
        sb.AppendLine();

        foreach (var item in injectables)
            sb.AppendLine($"{indent}    this.{item.Name} = ({item.Type})AppBuilderExtensions.ServiceProvider.GetService(typeof({item.Type.TrimEnd('?')}));");

        sb.AppendLine($"{indent}}}");
        sb.AppendLine($"{new string(' ', indentLevel * 4)}}}"); // Close View Class

        // Close Parent Classes
        while (parents.Count > 0)
        {
            parents.Pop();
            indentLevel--;
            sb.AppendLine($"{new string(' ', indentLevel * 4)}}}"); 
        }

        // Use a unique filename for nested types: "Outer_Inner.Inject.g.cs"
        var uniqueName = typeSymbol.ToDisplayString().Replace(".", "_").Replace("<", "").Replace(">", "");
        context.AddSource($"{uniqueName}.Inject.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}